"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/NavBar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PetCare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Navbar />

        <div className="h-screen ">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
